language: python

python:
  - "3.10"

before_install:
  - pip install poetry
install:
  - poetry install -v

script:
  - mkdocs build --verbose --clean --strict

deploy:
  provider: script
  script: git fetch origin gh-pages && mkdocs gh-deploy -v --clean --force
  on:
    branch: master
