version: "2.4"

services:
  redis:
    image: redis
    mem_limit: 128m
    mem_reservation: 32m
    cpus: 0.25
    volumes:
      - results_backend_data:/data
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:management
    mem_limit: 512m
    mem_reservation: 128m
    cpus: 0.5
    # Prevent huge memory usage by limiting the number
    # of file descriptors
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  results_backend_data: {}
