name: "Run CI"

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches:
      - "**"
      - "!gh-pages"

env:
  POETRY_VIRTUALENVS_CREATE: false

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3

      - name: Run docker-compose stack for testing
        run: make docker-up

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          # python-version: "^3.8"
          cache: "pip"
          cache-dependency-path: "poetry.lock"

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Lint
        run: make lint

      - name: Test
        # Wait for RabbitMQ to start.
        run: sleep 10 && make test

  test-build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "poetry.lock"

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - run: poetry run mkdocs build --verbose --clean --strict
