name: "Build docs"

on:
  push:
    branches:
      - main

env:
  POETRY_VIRTUALENVS_CREATE: false

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "poetry.lock"

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Build and push docs
        run: poetry run mkdocs gh-deploy --force
