name: Build and publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

env:
  POETRY_VIRTUALENVS_CREATE: false
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pip install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
          cache: 'pip'
          cache-dependency-path: 'poetry.lock'
      - name: Install dependencies
        run: poetry install
      - name: Build and publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --build
